### ISSUE TITLE
Ability 457 Issue

### ISSUE THREAD

**Issue by langerest** [jason-whitted/gloomy#38]
Card numbers for Cragheart, Mind Thief, two minis and possibly triangle (haven't unlocked it yet) are incorrect. These numbers have been changed after Isaac released the card pdfs.

The bottom action of two minis card 487 (457 in gloomy) was changed to Command: Loot 1 in second printing. The details of the second printing changes can be found at [Official Second Printing Change Log](https://boardgamegeek.com/thread/1761512/official-second-printing-change-log)

**Comment by jason-whitted** [comment]
I haven’t actually received my copy of Gloomhaven yet. Since I do not have the physical media I only have the online resources that I’ve scraped together.

When I get my copy I’ll go back in and update all of the ability IDs. Until then the ID displayed in Gloomy is the ID to reference. 

I can update ability 457 per your instructions. If anything else needs to get updated I’ll need explicit details.

**Comment by jason-whitted** [comment]
Fixed in 0.1.13
