### ISSUE TITLE
Remove Prosperity

### ISSUE THREAD

**Issue by Flaigebert** [jason-whitted/gloomy#78]
Hi,

removing prosperity is not working in my campaign. It's stated as 4 but if i remove either -1 or -2 nothing happens, it still remains in 4

**Comment by sjorsvanleeuwen** [comment]
That is working as intended as stated in the rules, once you hit prosperity level 2, you can't go back to level 1 (same goes for all other levels of prosperity, levels of checkmarks, xp. Only works for reputation).

**Comment by Flaigebert** [comment]
thanks you're right :) 
The error was on my side, i entered 2 prosperities to much, so i'm now stuck on level 2. Is there any way to get back, or do i need to start a new campaign?(or wait till we reach level 2 without any scenarios)

**Comment by sjorsvanleeuwen** [comment]
Depends how long ago it was you making the error, if not too long ago you could look it up in the history, delete the action and do it again.
It should also be doable by hacking it into the gists (though i would not recommend it!).
If it doesn't bother you too much, you could always keep it like this and keep it in mind next time you modify the prosperity tracker. (though that could also be difficult since scenario rewards could mess it up).

**Comment by Flaigebert** [comment]
i was able to do it via the history,
thanks a lot for all the support :)
